services:
  source-connector-event-hubs:
    build:
      context: .
    environment:
      AZURE_EVENT_HUB_CONNECTION_STRING: ${AZURE_EVENT_HUB_CONNECTION_STRING}
      AZURE_EVENT_HUB_CONSUMER_GROUP: ${AZURE_EVENT_HUB_CONSUMER_GROUP}
      AZURE_EVENT_HUB_NAME: ${AZURE_EVENT_HUB_NAME}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_BLOB_CONTAINER_NAME: ${AZURE_STORAGE_BLOB_CONTAINER_NAME}
      PIPELINE_ACCESS_TOKEN: ${PIPELINE_ACCESS_TOKEN}
      PIPELINE_ID: ${PIPELINE_ID}
      SPACE_ID: ${SPACE_ID}
