services:
  sink-connector-redis:
    build:
      context: .
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_DB: ${REDIS_DB}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_INDEX: ${REDIS_INDEX}
      PIPELINE_ACCESS_TOKEN: ${PIPELINE_ACCESS_TOKEN}
      PIPELINE_ID: ${PIPELINE_ID}
      PYTHONUNBUFFERED: 1