services:
  postgres:
    image: postgres:latest
    command: "-c wal_level=logical -c max_wal_senders=5 -c max_replication_slots=5"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./generator-sql:/docker-entrypoint-initdb.d

  # nats:
  #   extends:
  #     file: ../../connectors/source/postgresql/compose.yaml
  #     service: nats
  
  source-connector-nats:
    extends:
      file: ../../connectors/source/nats-jetstream/compose.yaml
      service: source-connector-nats
  
  debezium:
    image: docker.io/debezium/server:latest
    volumes:
      - ./application.properties:/debezium/conf/application.properties
    depends_on:
      - source-connector-nats
      # - nats
    extra_hosts:
      - "host.docker.internal:host-gateway"

