services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--debug"
      - "--http_port=8222"
      - "--js"
  source-connector-postgres:
    build:
      context: .
    environment:
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      PIPELINE_ACCESS_TOKEN: ${PIPELINE_ACCESS_TOKEN}
      PIPELINE_ID: ${PIPELINE_ID}
      SPACE_ID: ${SPACE_ID}
    depends_on:
      - nats  
  debezium:
    image: docker.io/debezium/server:latest
    volumes:
      - ./application.properties:/debezium/conf/application.properties
    depends_on:
      - source-connector-postgres
      - nats
    extra_hosts:
      - "host.docker.internal:host-gateway"  