services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--debug"
      - "--http_port=8222"
      - "--js"
  source-connector-nats:
    build:
      context: .
    environment:
      NATS_JETSREAM_URL: ${NATS_JETSREAM_URL}
      NATS_JETSREAM_SUBJECTS: ${NATS_JETSREAM_SUBJECTS}
      PIPELINE_ACCESS_TOKEN: ${PIPELINE_ACCESS_TOKEN}
      PIPELINE_ID: ${PIPELINE_ID}
      SPACE_ID: ${SPACE_ID}
    depends_on:
      - nats  
