services:
  sink-connector-redis:
    environment:
      REDIS_HOST: redis-stack
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${EMPTY:+STRING}
      REDIS_INDEX: idx
    extends:
      file: ../../connectors/sink/redis/compose.yaml
      service: sink-connector-redis

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    command:
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
